version: '3.7'

services:
  web:
    build: .
    command: python /new/manage.py runserver 0.0.0.0:8000
 #   command: gunicorn QuestionTime.wsgi -b 0.0.0.0:8000
 #   environment: 
 #     - ENVIRONMENT=development
 #     - SECRET_KEY=!@iur(@nyzce7hx3dzf$$!9*d8(6mtqhnie-4lmm1uoyxudr3%p
 #     - DEBUG=1
    volumes:
      - .:/new
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres

volumes: 
  postgres_data: